{% set name = "cerf" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://jugit.fz-juelich.de/mlz/libcerf/-/archive/v{{ version }}/libcerf-v{{ version }}.tar.gz
  sha256: 080b30ae564c3dabe3b89264522adaf5647ec754021572bee54929697b276cdc


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f "$PREFIX/lib/libcerf${SHLIB_EXT}"  # [unix]

about:
  home: https://jugit.fz-juelich.de/mlz/libcerf
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A self-contained numeric library that provides an efficient and accurate implementation of complex error functions, along with Dawson, Faddeeva, and Voigt functions.

extra:
  recipe-maintainers:
    - andyfaff
    - jwuttke
