{% set name = "cerf" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://jugit.fz-juelich.de/mlz/libcerf/-/archive/v{{ version }}/libcerf-v{{ version }}.tar.gz
  sha256: c86e8b1ea18ac7747582e83dba6f42f0faea1deb5005b7ffb2e508e36b579716


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}

test:
  commands:
    - test -f "$PREFIX/lib/libcerf${SHLIB_EXT}"  # [unix]

about:
  home: https://jugit.fz-juelich.de/mlz/libcerf
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A self-contained numeric library that provides an efficient and accurate implementation of complex error functions, along with Dawson, Faddeeva, and Voigt functions.

extra:
  recipe-maintainers:
    - andyfaff
    - jwuttke
